[target.riscv32imc-esp-espidf]
# runner = "espflash flash --monitor"
linker = "ldproxy"

[build]
target = "riscv32imc-esp-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c3"
# ESP_IDF_VERSION = "v5.2.2" # Optional: specify version
